### PR TITLE
Fix a race that can result in unnecessary fallback executions

### LINKED ISSUE #192: fetch sometimes executes fallback unnecessarily
Hi Isaac,

Thanks for publishing cachex, it looks great.

I was poking at `fetch` with a `fallback` where the fallback function would [`fetch` another key](https://github.com/ivan/trycachex/blob/1e1e6b3a482bcbee21d876dd93fd558eba509c76/lib/trycachex.ex#L47), and noticed that the fallback was called twice for that key, even though Cachex could have waited very briefly for the value to appear in the cache (because it was already fetched in parallel).  Is this a bug?

I have a repro case:

```
git clone https://github.com/ivan/trycachex
cd trycachex
mix deps.get
MIX_ENV=prod mix escript.build
./trycachex parallel
```

```
# ./trycachex parallel
get :thing1
get :thing2
get :superthing
get :subthing
waiting for subthing
get :subthing
waiting for subthing
%{
  subthing: "subthing!",
  superthing: "superthing with subthing!!",
  thing1: "thing one!",
  thing2: nil
}
```

(Note two `"waiting for subthing"`)

Thanks,

Ivan

### PR DESCRIPTION
**Pull request by ivan**
This fixes #192.

I confirmed that the new test fails with `lib/cachex/services/courier.ex` from the previous commit, e719293bbd80c8b17b8af4e5e79102ed74ef84a7.

### CODE REVIEW

**Comment by whitfin** [comment]
@ivan thanks for this. I'm still not willing to accept that this is the only way to fix it though; I'm going to look a little more into it - the server should be protecting us against race conditions. I want to rule out a bug elsewhere in the codebase.

File: lib/cachex/services/courier.ex [hunk 1]
```diff
@@ -91,13 +97,7 @@ defmodule Cachex.Services.Courier do
...
   # This will update all processes waiting for the result of the
   # specified task, and remove the task from the tracked state.
-  def handle_info({ :notify, key, result }, { cache, tasks }) do
-    normalized = normalize_commit(result)
-
-    with { :commit, val } <- normalized do
-      Put.execute(cache, key, val, const(:notify_false))
-    end
-
+  def handle_info({ :notify, key, normalized }, { cache, tasks }) do
```
Comment (whitfin) [inline lib/cachex/services/courier.ex]: Can you please change `normalized` back to `result`?

File: lib/cachex/services/courier.ex [hunk 2]
```diff
@@ -76,7 +76,13 @@ defmodule Cachex.Services.Courier do
               rescue
                 e -> { :error, Exception.message(e) }
               end
-            send(parent, { :notify, key, result })
+            # Commit the result immediately to avoid a race in fetch
+            # between Get.execute and Courier.dispatch.
+            normalized = normalize_commit(result)
```
Comment (whitfin) [inline lib/cachex/services/courier.ex]: For this block, please keep the same spacing from before:

```
normalized = normalize_commit(result)

with { :commit, val } <- normalized do
  Put.execute(cache, key, val, const(:notify_false))
end

send(parent, { :notify, key, normalized })
```

File: lib/cachex/services/courier.ex [hunk 3]
```diff
@@ -76,7 +76,13 @@ defmodule Cachex.Services.Courier do
               rescue
                 e -> { :error, Exception.message(e) }
               end
-            send(parent, { :notify, key, result })
+            # Commit the result immediately to avoid a race in fetch
```
Comment (whitfin) [inline lib/cachex/services/courier.ex]: You can drop this comment; I'll address it later in the doc comments.

File: test/cachex/actions/fetch_test.exs [hunk 4]
```diff
@@ -95,4 +95,32 @@ defmodule Cachex.Actions.FetchTest do
     assert(result8 == { :error, :invalid_fallback })
     assert(result9 == { :error, :invalid_fallback })
   end
+
+  # This test ensures that the fallback is executed just once when a
+  # fallback commit and another fetch on the same key occur simultaneously.
+  test "fetching and committing the same key simultaneously from a fallback" do
+    for duration <- 1..10 do
```
Comment (whitfin) [inline test/cachex/actions/fetch_test.exs]: Does this set of test code really need to run 10 times? I know it's because of the change in duration, but can we not just pick `50` as a duration (or w/e), since it should be the same behaviour?

File: lib/cachex/services/courier.ex (hunk 1 above)
Comment (ivan) [reply lib/cachex/services/courier.ex]: I changed what I pass in to `handle_info`; should I call `normalize_commit(result)` again there?

File: lib/cachex/services/courier.ex (hunk 2 above)
Comment (ivan) [reply lib/cachex/services/courier.ex]: OK, will do

File: lib/cachex/services/courier.ex (hunk 3 above)
Comment (ivan) [reply lib/cachex/services/courier.ex]: OK, will do

File: lib/cachex/services/courier.ex (hunk 1 above)
Comment (whitfin) [reply lib/cachex/services/courier.ex]: No, it's fine - just the name should be `result` here because there's no context as to what `normalized` means anymore :)

File: test/cachex/actions/fetch_test.exs (hunk 4 above)
Comment (ivan) [reply test/cachex/actions/fetch_test.exs]: Because the test doesn't always fail even when set up carefully, I run it 10 times to increase the chance of the wrong implementation failing the test. Even when run 10 times, it doesn't always fail on some machines. But the duration might not need to change, so I will investigate and maybe tweak this.

Comment (whitfin) [reply test/cachex/actions/fetch_test.exs]: Ah, I see. Is it possible to lift the test you had in that repo you linked me to? I don't mind if the test takes a second or two.

Comment (ivan) [reply test/cachex/actions/fetch_test.exs]: This test basically does the same thing as what was in the test repo, but is compatible with old versions of Elixir. Since you don't mind it running longer, I'll see if I can decrease its false successes by raising the number of iterations.

**Comment by ivan** [comment]
I force-pushed with everything addressed, hopefully.  I removed the unnecessary sleeps from the test and changed `key2_fallback` to match `key1_fallback`'s execution time more closely.  Now (with the incorrect implementation) it almost always fails on the first or second iteration, but sometimes the third.  I left ten iterations in case the stars don't align repeatedly.

**Comment by whitfin** [comment]
@ivan perfect; thank you! I'll push this up shortly.
